CREATE TABLE LEG
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    START_VERTEX INT(11) NOT NULL,
    END_VERTEX INT(11) NOT NULL,
    MAX_WEIGHT DOUBLE NOT NULL
);
CREATE TABLE CLIENT
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT
);
CREATE TABLE PRODUCT
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    WEIGHT DOUBLE NOT NULL,
    PRICE DOUBLE,
    ORDER_ID INT(11) NOT NULL,
    CONSTRAINT PRODUCT_ORDER_ID_fk FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID)
);
CREATE INDEX PRODUCT_ORDER_ID_fk ON PRODUCT (ORDER_ID);
CREATE TABLE ORDERS
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    START_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLIENT_ID INT(11) NOT NULL,
    START_VERTEX INT(11) NOT NULL,
    END_VERTEX INT(11) NOT NULL,
    CONSTRAINT ORDER_CLIENT_ID_fk FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID)
);
CREATE INDEX ORDER_CLIENT_ID_fk ON ORDERS (CLIENT_ID);
CREATE TABLE ROUTE
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ORDER_ID INT(11) NOT NULL,
    CONSTRAINT ROUTE_ORDERS_ID_fk FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID)
);
CREATE INDEX ROUTE_ORDERS_ID_fk ON ROUTE (ORDER_ID);
CREATE TABLE ROUTE_LEG
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    LEG_ID INT(11) NOT NULL,
    ROUTE_ID INT(11) NOT NULL,
    CONSTRAINT ROUTE_LEG_LEG_ID_fk FOREIGN KEY (LEG_ID) REFERENCES LEG (ID),
    CONSTRAINT ROUTE_LEG_ROUTE_ID_fk FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE (ID)
);
CREATE INDEX ROUTE_LEG_LEG_ID_fk ON ROUTE_LEG (LEG_ID);
CREATE INDEX ROUTE_LEG_ROUTE_ID_fk ON ROUTE_LEG (ROUTE_ID);